name: 'Apache PHP'
description: 'Use after shivammathur/setup-php to use Apache. Logs will be written to the working directory.'
inputs:
  php-version:
    description: 'Setup PHP version. Must match the PHP version used by shivammathur/setup-php'
    required: true
  site-directory:
    description: 'The site directory for Apache to serve'
    required: true
  http-port:
    description: 'The port for Apache to listen to HTTP requests'
    default: 8888\
# Install Apache and configure to serve the site under test. Apache is run
# in the foreground using the same user as the test runner to avoid common
# pitfalls with file ownership. This action also disables xdebug if it has
# resulted in it being installed.
runs:
  using: "composite"
  steps:
    - name: Install Apache with mod_php
      run: |
        WAS_XDEBUG_INSTALLED=`php -r "echo extension_loaded('xdebug');"`
        LC_ALL=C.UTF-8 sudo apt-add-repository http://ppa.launchpad.net/ondrej/php/ubuntu
        sudo apt install libapache2-mod-php${{ inputs.php-version }}
        sudo a2enmod php${{ inputs.php-version }} rewrite
        IS_XDEBUG_INSTALLED=`php -r "echo extension_loaded('xdebug');"`
        echo "IS_XDEBUG_INSTALLED=$IS_XDEBUG_INSTALLED and WAS_XDEBUG_INSTALLED=$WAS_XDEBUG_INSTALLED"
        if [ "$IS_XDEBUG_INSTALLED" == "1" && "$WAS_XDEBUG_INSTALLED" != "1" ]; then sudo phpdismod xdebug; fi;
      shell: bash
    - name: Configure the site under test
      run: |
        echo "<Directory ${{ inputs.site-directory }}>" | sudo tee /etc/apache2/sites-available/sut.conf
        echo '  Options Indexes FollowSymLinks' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '  AllowOverride all' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '  Require all granted' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '</Directory>' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo "<VirtualHost *:${{ inputs.http-port }}>" | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '  ServerAdmin admin@localhost' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo "  DocumentRoot ${{ inputs.site-directory }}" | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '  ErrorLog ${APACHE_LOG_DIR}/error.log' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '  CustomLog ${APACHE_LOG_DIR}/access.log combined' | sudo tee -a /etc/apache2/sites-available/sut.conf
        echo '</VirtualHost>' | sudo tee -a /etc/apache2/sites-available/sut.conf
        sudo sed -ri -e "s!Listen 80!Listen ${{ inputs.http-port }}!g" /etc/apache2/ports.conf
        sudo a2ensite sut
        sudo a2dissite 000-default
      shell: bash
    - name: Start Apache in the foreground
      run: |
        source /etc/apache2/envvars
        export APACHE_LOG_DIR="${PWD}"
        export APACHE_LOCK_DIR="${PWD}"
        export APACHE_PID_FILE="${PWD}/apache2.pid"
        nohup apache2 -DFOREGROUND > /dev/null 2>&1 &
        sleep 2
        nc -z "127.0.0.1" "${{ inputs.http-port }}"
      shell: bash
